<div class="content">
    <?php $this->load->view('frontend/element/vcontentleft'); ?>
    <div class="center_all" style="width: 70%;min-height: 384px">
        <h2>Sarana Prasarana :</h2>

        <ul>
            <li>
                Luas Tanah                            : 35.943 M2
            </li>
            <li>Luas Bangunan                       : 12.075</li>
            <li>Jumlah Bangunan                    : 6 Gedung</li>
        </ul>

        <p>
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
            dhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcjdhbhsjjsjsjcbscbjdhsbcjsbcj
        </p>

    </div>
</div>
